name: Pages

on:
  push:
    branches:
      - main
      - data

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: "main"

      - name: Checkout data branch
        uses: actions/checkout@v2
        with:
          ref: "data"
          path: "data"

      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: "gh-pages"
          path: "gh-pages"

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Export data to flat JSON files
        run: python3 data/export_db.py data/data.sql gh-pages/
