name: Pages

on:
  push:
    branches:
      - main
      - data

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: "main"

      - name: Checkout data branch
        uses: actions/checkout@v2
        with:
          ref: "data"
          path: "data"

      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: "gh-pages"
          path: "gh-pages"

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Load SQLite database
        run: sqlite3 data/data.sqlite3 <data/data.sql
        
      - name: Get indexes
        run: sqlite3 data.sqlite3 '.indexes'
        
      - name: Clean gh-pages artifacts
        run: rm -r *
        working-directory: gh-pages/

      - name: Export data to flat JSON files
        run: python3 export_db.py data/data.sqlite3 gh-pages/

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit --message "Export database" || true
        working-directory: gh-pages/

      - name: Push changes
        run: git push
        working-directory: gh-pages/
