name: Pages

on:
  push:
    branches:
      - main
      - data

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: "main"

      - name: Checkout data branch
        uses: actions/checkout@v2
        with:
          ref: "data"
          path: "data"

      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: "gh-pages"
          path: "gh-pages"

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Load SQLite database
        run: sqlite3 data/data.sqlite3 <data/data.sql

      - name: Get database indexes
        run: |
          INDEXES=$(sqlite3 data/data.sqlite3 '.indexes')
          echo "INDEXES=$INDEXES" | tee -a $GITHUB_ENV

      - name: Clean gh-pages index directories
        run: |
          set -x
          for index in $INDEXES; do
              rm -rf "gh-pages/$index"
              mkdir -p "gh-pages/$index"
          done

      - name: Export data to flat JSON files
        # run: python3 export_db.py data/data.sqlite3 gh-pages/
        run: |
          #/usr/bin/env python3

          import json
          import os
          import sqlite3
          import sys

          con = sqlite3.connect(sys.argv[1])
          con.row_factory = sqlite3.Row

          root = sys.argv[2]

          index_names = os.environ["INDEXES"].split()

          for result in con.execute("SELECT * FROM movies"):
              row = dict(result)

              for index_name in index_names:
                  filename = "{}.json".format(result[index_name])
                  filename = os.path.join(root, index_name, filename)

                  with open(filename, "w") as f:
                      json.dump(row, f, indent=2)
                      f.write("\n")

      - name: Commit changes
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'joshbot@users.noreply.github.com'
          git add .
          git commit --message "Export database" || true
        working-directory: gh-pages/

      - name: Push changes
        run: git push
        working-directory: gh-pages/
