name: Pages

on:
  schedule:
    - cron: "20 0,16 * * *"
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout data branch
        uses: actions/checkout@v2

      - name: Checkout code branch
        uses: actions/checkout@v2
        with:
          ref: "main"
          path: "script"

      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: "gh-pages"
          path: "gh-pages"

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r script/requirements.txt

      - name: Load SQLite database
        run: sqlite3 data.sqlite3 <data.sql

      - name: Export database
        run: python3 script/export_database.py -vv --database data.sqlite3 --output gh-pages/

      - name: Commit changes
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'joshbot@users.noreply.github.com'
          git add .
          git commit --message "Export database ${{ github.sha }}" || true
        working-directory: gh-pages/

      - name: Push changes
        run: git push --force origin refs/heads/gh-pages
        working-directory: gh-pages/
