name: Pages

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout data branch
        uses: actions/checkout@v2

      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: "gh-pages"
          path: "gh-pages"

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Load SQLite database
        run: sqlite3 data.sqlite3 <data.sql

      - name: Get database indexes
        run: |
          INDEXES=$(sqlite3 data.sqlite3 '.indexes')
          echo "INDEXES=$INDEXES" | tee -a $GITHUB_ENV

      - name: Clean gh-pages index directories
        run: |
          set -x
          for index in $INDEXES; do
              rm -rf "gh-pages/$index"
              mkdir -p "gh-pages/$index"
          done

      - name: Export data to flat JSON files
        run: python3 export_db.py data.sqlite3 gh-pages/

      - name: Commit changes
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'joshbot@users.noreply.github.com'
          git add .
          git commit --message "Export database" || true
        working-directory: gh-pages/

      - name: Push changes
        run: git push
        working-directory: gh-pages/
