name: Pages

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout data branch
        uses: actions/checkout@v2

      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: "gh-pages"
          path: "gh-pages"

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Load SQLite database
        run: sqlite3 data.sqlite3 <data.sql

      - name: Get database indexes
        run: |
          INDEXES=$(sqlite3 data.sqlite3 '.indexes')
          echo "INDEXES=$INDEXES" | tee -a $GITHUB_ENV

      - name: Clean gh-pages index directories
        run: |
          set -x
          for index in $INDEXES; do
              rm -rf "$index"
              mkdir -p "$index"
          done
        working-directory: gh-pages/

      - name: Export data to flat JSON files
        run: |
          python3 <<PY
          import json
          import os
          import sqlite3

          con = sqlite3.connect("data.sqlite3")
          con.row_factory = sqlite3.Row
          indexes = os.environ["INDEXES"].split()

          for row in con.execute("SELECT * FROM movies"):
              for name in indexes:
                  filename = os.path.join("gh-pages", name, row[name] + ".json")
                  print(filename)
                  with open(filename, "w") as f:
                      json.dump(dict(row), f, indent=2)
                      f.write("\n")
          PY

      - name: Commit changes
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'joshbot@users.noreply.github.com'
          git add .
          git commit --message "Export database" || true
        working-directory: gh-pages/

      - name: Push changes
        run: git push
        working-directory: gh-pages/
