name: Pages

on:
  push:
    branches:
      - main
      - data

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: "main"

      - name: Checkout data branch
        uses: actions/checkout@v2
        with:
          ref: "data"
          path: "data"

      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: "gh-pages"
          path: "gh-pages"

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Load SQLite database
        run: sqlite3 data/data.sqlite3 <data/data.sql

      - name: Clean gh-pages index directories
        run: |
          set -x
          indexes=$(sqlite3 data/data.sqlite3 '.indexes')
          for index in $indexes; do
              rm -rf "gh-pages/$index"
              mkdir -p "gh-pages/$index"
          done

      - name: Export data to flat JSON files
        run: python3 export_db.py data/data.sqlite3 gh-pages/

      - name: Commit changes
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'joshbot@users.noreply.github.com'
          git add .
          git commit --message "Export database" || true
        working-directory: gh-pages/

      - name: Push changes
        run: git push
        working-directory: gh-pages/
