name: Tasks

on:
  schedule:
    - cron: "15 0,16 * * *"
  push:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Checkout code branch
        uses: actions/checkout@v2
        with:
          ref: "main"
          path: "script"

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Load SQLite database
        run: sqlite3 data.sqlite3 <data.sql

      - name: Update database
        run: python3 update_data.py -vv --database data.sqlite3

      - name: Dump SQLite database
        run: sqlite3 data.sqlite3 '.dump'>data.sql

      - name: Commit changes
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'joshbot@users.noreply.github.com'
          git add data.sql
          git commit --message "Update data" || true

      - name: Push changes
        run: git push
