name: Tasks

on:
  schedule:
    - cron: "15 0,16 * * *"
  push:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Checkout code branch
        uses: actions/checkout@v2
        with:
          ref: "main"
          path: "script"

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r script/requirements.txt

      - name: Load SQLite database
        run: sqlite3 data.db <data.sql

      - name: Discover items
        run: python3 script/discover_items.py -vv --database data.db
        env:
          TRAKT_CLIENT_ID: ${{ secrets.TRAKT_CLIENT_ID }}

      - name: Update database
        run: python3 script/update_data.py -vv --database data.db

      - name: Sort table row ids
        run: python3 script/reinsert_database_table.py --database data.db --table items --order-by 'CAST(LTRIM(wikidata_qid,"Q") AS INTEGER), imdb_id'

      - name: Dump SQLite database
        run: sqlite3 data.db '.dump'>data.sql

      - name: Commit changes
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'joshbot@users.noreply.github.com'
          git add data.sql
          git commit --message "Update data" || true

      - name: Push changes
        run: git push
